WIDTH = 1024
HEIGHT = 768
DISPLAY_CENTER = (WIDTH/2, HEIGHT/2)
FONT = 'modules/assets/fonts/Tigerious.otf'
FROG = 'modules/assets/images/frog.png'
SKULL = 'modules/assets/images/skull.png'
LIFE = 'modules/assets/images/live.png'
BOMB = 'modules/assets/images/bomb.png'
ARROW = 'modules/assets/images/arrow.png'
FONT_SIZE = 20
BALL_DIAMETER = 40
