name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python -m pytest
      - name: Check coverage
        run: |
          SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy python -m pytest --cov=modules